[클린코드 2기 추연호] 계산기 미션
next-step/js-calculator pull request #104
Opened 2022-03-12 17:56 UTC by younho9

안녕하세요. 클린코드 2기 추연호입니다.

[계산기 미션 실행](https://younho9.github.io/js-calculator/)
[테스트 실행 결과](https://github.com/younho9/js-calculator/actions/workflows/main.yml)

## 🎯 기능 요구사항

- [x] 2개의 숫자에 대해 덧셈이 가능하다.
- [x] 2개의 숫자에 대해 뺄셈이 가능하다.
- [x] 2개의 숫자에 대해 곱셈이 가능하다.
- [x] 2개의 숫자에 대해 나눗셈이 가능하다.
- [x] AC(All Clear)버튼을 누르면 0으로 초기화 한다.
- [x] 숫자는 한번에 최대 3자리 수까지 입력 가능하다.
- [x] 계산 결과를 표현할 때 소수점 이하는 버림한다.

## 📊 테스트 요구사항

- [x] 기능 요구사항에 제시된 7개의 항목에 대해 테스트 케이스를 만든다.

## 🗒 고려한점

- `null` 대신 `undefined` 만을 사용해봤습니다. 다른 분들은 이에 대해 어떻게 생각하시는 지 궁금합니다.
    - 이유 ?
		- `typeof null === 'object'` 는 대표적인 자바스크립트 설계상 실수로 알려짐.
		- 둘 다 지원하는 것보다 하나만 지원하는 것이 유효성 검사를 단순하게 할 수 있다.
		- 기본 매개변수와 같은 최신 JS 기능은 `undefined` 를 사용한다.
	- 참고
		- https://2ality.com/2013/10/typeof-null.html
		- https://github.com/sindresorhus/meta/discussions/7
		- https://blog.shiren.dev/2021-10-05/
- iOS / MacOS 기본 계산기 앱의 동작과 비교해보면서 몇 가지 기능 요구사항을 추가해봤습니다.
	- 추가 기능 요구사항
		- [x] 계산 결과에 이어 숫자를 클릭하면, 새로운 연산이 가능하다.
		- [x] 계산 결과에 이어 연산자를 클릭하면, 계산 결과에 이어서 추가적으로 연산이 가능하다.
		- [x] 계산 결과에 이어 `=` 연산자를 클릭하면, 이전 계산 결과가 계속 나타난다.
	- 계산기의 표시 창에 어떤 상태일 때는 결과 값을 표시하고, 어떤 상태일 때는 인풋 값을 표시하는데, 이 상태를 어떻게 표현하고 구분할 것인지가 어렵게 느껴졌습니다.
		- 다른 분들은 계산기의 상태를 어떻게 표현하실 지 궁금합니다.
- cypress 테스트 구조화
	- `cy` 가 `Chainable` 한 것으로 알고 있는데, 하나의 테스트 케이스에서 `cy` 를 계속 체이닝해서 쓰는게 좋은지, 중간중간 끊어서(?) 사용하는게 좋은지 궁금합니다.
		- `cy` 체이닝이 길어서 그런건지 cypress 브라우저 테스트에서는 통과하는데 headless 테스트에서 실패하는 경우가 있는 것 같습니다.
			- https://docs.cypress.io/guides/references/error-messages#cy-failed-because-the-element-you-are-chaining-off-of-has-become-detached-or-removed-from-the-dom
	- 하나의 테스트(`it` 또는 `test`)에서도 여러 개의 테스트 케이스가 있을 것 같은데 (ex. `3 + 3`, `40 + 60`, ...) 테스트 케이스가 하나만 있는 것도 찝찝하고, 그렇다고 무수히 많은 것도 관리가 어려울 것 같아서, 어떤 기준으로 테스트 케이스를 추가하는 것이 좋을 지 궁금합니다.

2022-03-14 15:21 UTC, pocojang requested changes
안녕하세요
@younho9님

리뷰어 장현석입니다.

코드에 굉장히 많은 시간을 들이시고 꼼꼼하게 신경쓰신 것들 굉장히 보기 좋네요.
하지만 이번 미션 자체는 온보딩 미션이기 때문에 몇가지 소소한 코멘트만 남겼습니다 :)

제가 보기에는 이미 `JavaScript`를 어느 정도 코드를 작성하신 티가 나기 때문에 앞으로 미션을 쉽게 잘 하실 것이라는 기대감이 듭니다.

---

고려한 점 이야기

## null 대신 undefined 만을 사용

이 부분은 의견이 굉장히 분분합니다.
JS의 발전 TS 사용까지 더해지니 점점 더 다양한 의견들이 도출되는데요
저 같은 경우에도 undefined를 선호합니다.

참고로 가져온 코드도 상당히 신빙성 있는 분들의 자료를 가져오셨네요 ㅎㅎ
저 또한 모두 존경하는 분들입니다.

## 계산기의 상태 표시

`eval`을 사용할 이유도 꼭 찾아야할 이유도 없어 보입니다.
과거의 유산이지만 과거에서도 지양하자는 이야기가 많죠.

언어가 점점 발전하는데 굳이 `eval`을 활용할 이유는 더더욱 없어보여요
또한 `new Function()`을 사용할 이유도 없어보이는데 코드가 더 길어지더라도 달콤함의 유혹을 참아야겠죠 ㅎㅎ

물론 스터디를 하는 단계에서는 당연히 문제 없어보이고요
이런 사소한 것에도 궁금증을 가지는 자세가 훌륭하십니다

## cy 체이닝

저 또한 같은 경험을 해봤습니다
여러가지로 의도대로 안되는 경우가 많더라고요...
좋은 레퍼런스 감사합니다

가끔을 슬랙에도 공유 부탁드려요 💯 

## 테스트 케이스 개수

팀에서의 협의, 프로젝트의 상황마다 다른 부분이 너무나 많은 것이 달라지죠.

프론트 생태계는 더더욱 그런게 많죠.

나만의 기준을 먼저 만들기보다는 애플리케이션 구성마다 테스트의 커버리지, 단위 등을 어떻게 가져갈 것인가를 먼저 선행하셔야 그 다음 작은 단위의 구성도 하실 수 있을 것이라 봅니다

이 부분은 RTL의 창시자 [Kent C. Dodds](https://kentcdodds.com)의 아티클을 많이 읽어보시는 것을 추천합니다.

그는 테스트 트로피를 강조하는데 그 정신과 이념이 꽤나 모던하거든요 :)

## JSDoc

any가 많이 보여서 그런지 불필요한 부분이 생각보다 많아보이네요 (물론 JSDoc 탓)
차라리 TS를 쓰는게 어떤가 싶기도 하긴했고요

온보딩부터 정성이 엄청나게 담겨있어 리뷰하기 즐거웠습니다
그럼 `Request Changes` 드립니다만 원하시면 바로 `Approve`전환하겠습니다

2022-03-14 15:21 UTC, pocojang commented on README.md
> +  <a href="https://younho9.github.io/js-calculator/">🖥️ 데모 링크</a>
👍

2022-03-14 15:21 UTC, pocojang commented on index.html
>  <html lang="en">
저희가 놓친 것이라 솔직 고백하자면 `ko`가 더 어울리겠네요 ㅎㅎ

2022-03-14 15:21 UTC, pocojang commented on src/js/constants/index.js
> +	eq: '=',
상수의 속성들은 갑자기 `lowercase`라서 어색하네요 ㅎㅎ
또한 속성의 네이밍들이 꽤나 축약된 것으로 보이는데 @younho9 님은 어떻게 생각하시나요?

2022-03-14 15:21 UTC, pocojang commented on src/js/constants/index.js
> +	add: '+',
`add`는 의미상 안어울리지 않나요?

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +			}
```js
return false
```
는 무엇을 기대하고 넣으신걸까요?

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +			return true;
👍

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +				$display.innerText = findLastNumber(value) ?? target.result;
`proxy` 내부에서 직접적으로 `DOM`에 접근하는건 어울리지는 않아보이네요
다만 구조적인 부분은 계산기정도 수준의 작은 앱이라 적합한 결정으로 보입니다

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +const state = new Proxy(
`proxy` 적용 좋네요
계산기인데 굳이 `proxy`가 필요할까? 했지만 나름 합리적으로 적절하게  쓰신 것으로 보입니다

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +$calculator.addEventListener('click', (event) => {
이벤트 위임 활용 좋군요
다만 `target`에 계속 접근하시니 미리 꺼내 쓰시는 것도 좋겠네요

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +	const lastInput = state.expression.at(-1);
👍

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +		alert(ALERT_MAX_NUMBER_LENGTH_MESSAGE);
👍

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +		}
흠 뎁스를 줄일 수 있을 것 같은데 뭔가 좀 아쉽네요

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +const isOperation = (value) => Object.values(OPERATIONS).includes(value);
`is-`보다는 다른 `prefix`가 더 적절해보이기도하는데 애매하네요

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +const isHTMLElement = (element) => element instanceof HTMLElement;
👍

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +const isOperationButton = (element) => element.classList.contains('operation');
`classList`로 검사하는데 버튼인지는 검사안하고 이래저래 아쉬운 부분이 있어서 아쉬운 감이 있습니다

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +	return Math.trunc(calculator());
정말 재미있는 코드네요ㅎㅎ
좋은 인사이트 받아갑니다.

팀 단위로 생각했을때 이런 코드를 보면 애매하다고 느껴지는데요.
리뷰어로서는 흥미로운데요

141번 라인처럼 함수를 생성하는 것에 효용성이 있으셨을까요~?

2022-03-14 15:21 UTC, pocojang commented on src/js/index.js
> +	return [...expression].reverse().find((value) => !isOperation(value));
👍

2022-03-14 15:21 UTC, pocojang commented on package.json
> +		"@younho9/prettier-config": "^2.3.1",
와우 어마어마하네요 👍

2022-03-14 15:24 UTC, pocojang commented on cypress/support/commands.js
> +});
👍

2022-03-15 13:44 UTC, younho9 commented on src/js/constants/index.js
> +	eq: '=',
> 상수의 속성들은 갑자기 lowercase라서 어색하네요 ㅎㅎ

그렇네요 ㅎㅎ 

기호별 표준적인 이름을 찾아서 쓰는 걸로 수정했는데, 기호 자체를 키로 쓰는게 나을지 고민되는 부분이네요.

> 또한 속성의 네이밍들이 꽤나 축약된 것으로 보이는데 @younho9 님은 어떻게 생각하시나요?

축약된 네이밍보다는 길더라도 표준적인(보편적인) 이름을 사용하는게 훨씬 나은 것 같습니다. 가능한 많은 사람이 동일하게 읽고 이해할 수 있어야 하니까요.
평소 사용하는 eslint 설정으로 [unicorn/prevent-abbreviations](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prevent-abbreviations.md) 룰을 포함하고 있는데, 이런 도구의 지원이 없으면 사람은 가끔 실수하게 되는 것 같습니다 ㅎㅎ

2022-03-15 13:46 UTC, younho9 commented on src/js/constants/index.js
> +	add: '+',
`add` 보다는 [`addition`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Addition) 또는 `plus`가 나은 것 같습니다. 
직접 `+`로 쓰는 건 어떨지 @pocojang 님 생각이 궁금합니다! (만약 가능하다면 `OPERATIONS`가 배열이 될 수도 있을 것 같아요.)

2022-03-15 14:04 UTC, younho9 commented on src/js/index.js
> +			}
> [[Set]] for Proxy objects enforces the following invariants:
>	- The result of [[Set]] is a Boolean value.
> 
> https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-set-p-v-receiver
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/set#return_value

`Proxy`의 `set`이 `Boolean`을 리턴해야 한다는 규칙이 있는걸로 알고 따르고 있었습니다.

이번 기회로 테스트해보니, `return` 으로 변경해도 `return false` 와 같이 `TypeError`를 발생시키는 것을 확인했습니다. `return false` 보다 `return` 이 다른 사람이 보기에 더 좋을 것 같습니다.

추가로 에러 메시지를 통해서 `falsish` 라는 용어를 새로 접하게 되었네요 ㅎㅎ

```
Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'a'
    at HTMLDivElement.<anonymous> (index.js:16:11)
```

2022-03-15 14:56 UTC, younho9 commented on src/js/index.js
> +				$display.innerText = findLastNumber(value) ?? target.result;
> proxy 내부에서 직접적으로 DOM에 접근하는건 어울리지는 않아보이네요

그런 것 같습니다! 

`Proxy` 내부에서 직접 변경하지 않고, 이벤트를 전파하여 `DOM` 조작부와 느슨하게 결합시키는 것으로 개선해봤습니다!

2022-03-15 15:00 UTC, younho9 commented on src/js/index.js
> +const state = new Proxy(
이번 스터디를 통해서 실험적으로 사용해봤어요.. ㅎㅎ

전역 상태를 관찰(`Watch`)하고 변경 시 적절한 액션을 중앙에서 관리하는 스토어로 사용하고 싶은 생각이었는데, 아직 좀 미흡한 것 같네요.
좋게 말씀해주셔서 감사합니다.

2022-03-15 15:06 UTC, younho9 commented on src/js/index.js
> +		}
함수를 분리하는 방법으로 뎁스를 줄여봤는데요.

개인적으로

- 조건문에 가능하면 부정문보다 긍정문 사용
- 조건문에 가능하면 한 가지 조건만 사용
- 복잡한 조건은 함수로 분리하여 사용

위와 같은 선호도/기준 이 생겼는데, 계속 유지하면 좋은 기준일지 다른 기준을 우선해야할 지 궁금합니다!
(물론, 말씀해주신 뎁스를 줄이는 것은 위의 기준과 비교했을 때 더 우선순위가 있는 것 같다고 생각합니다.)

2022-03-15 15:13 UTC, younho9 commented on src/js/index.js
> +const isOperation = (value) => Object.values(OPERATIONS).includes(value);
제가 보기에도 좀 애매한 것 같습니다..

혹시 애매한 포인트가 계산기 애플리케이션 도메인에서의 `Operation`과 더 넓은 범위의 `Operation`의 용어 사이에서 오는 걸까요?
`isSupportedOperator` 와 같은 네이밍 정도가 떠오르네요..

`Boolean`에 대해서는 이 정도 `prefix`를 사용하고 있는데, 추가적으로 유용한 `prefix`가 더 있을지 궁금합니다!

```
prefix: [
	'is',
	'has',
	'can',
	'should',
	'will',
	'did'
]
```

> https://github.com/xojs/eslint-config-xo-typescript/blob/main/index.js#L38-L45

2022-03-15 15:14 UTC, younho9 commented on src/js/index.js
> +const isOperationButton = (element) => element.classList.contains('operation');
`isButton` 을 추가해봤습니다!

2022-03-15 15:45 UTC, younho9 commented on src/js/index.js
> +	return Math.trunc(calculator());
> 팀 단위로 생각했을때 이런 코드를 보면 애매하다고 느껴지는데요.

저도 말씀을 듣고보니 확실히 팀 단위로 생각하면 지양해야 될 것 같네요.
이런 사례가 소스에 들어오게 되면, 다른 팀원이 위험성은 인식하지 못한 채 레퍼런스로 참고되는 경우가 생길 것 같아요.

> 141번 라인처럼 함수를 생성하는 것에 효용성이 있으셨을까요~?

연산자 우선순위를 어떻게 구현할까? 고민하면서 현재 스펙 이상의 연산자들을 생각해보면 엄청 많을 것 같았고, 각 연산자 마다 우선순위를 정하기 너무 어려울 것 같았는데요. 

그러다보니 JavaScript가 이미 내부적으로 구현해놓은 연산자 우선순위 규칙을 사용하는 방법을 호기심으로 시도해본 것 같습니다.

`eval`을 사용하는 것과 비교했을 때 `Function`이 보안상으로 그나마(?) 나은 점은 "생성자가 호출된 범위의 변수에는 접근할 수 없다"는 점인 것 같아요.
 - https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Function#function_%EC%83%9D%EC%84%B1%EC%9E%90%EC%99%80_%ED%95%A8%EC%88%98_%EC%84%A0%EC%96%B8%EC%9D%98_%EC%B0%A8%EC%9D%B4

그렇다 하더라도 함수를 동적으로 평가하는 것이 보안 위험이 있을 수 있기 때문에, 두 가지 모두 Best Practice는 아니라는 점을 이번 기회에 확실히 배운 것 같습니다.
- https://2ality.com/2014/01/eval.html#:~:text=You%20should%20avoid%20eval()%20and%20new%20Function().

2022-03-15 15:52 UTC, pocojang commented on src/js/constants/index.js
> +	eq: '=',
역시 이미 잘 알고 계시는군요 ㅎㅎ

2022-03-15 15:53 UTC, pocojang commented on src/js/constants/index.js
> +	add: '+',
`OPERATIONS`에 포함된 다른 친구들을 비교해볼 수 있습니다
반의어를 찾아볼 수도 있지요ㅎㅎ
저 같으면 `sum`을 생각하거나 `lodash`와 같은 주로 사람들이 많이 사용하는 라이브러리 네이밍도 많이 참고합니다

2022-03-15 15:53 UTC, pocojang commented on src/js/index.js
> +			}
덕분에 좋은 공부 했습니다 :)
저도 몰랐던 내용이 있네요

2022-03-15 15:53 UTC, pocojang commented on src/js/index.js
> +const isOperationButton = (element) => element.classList.contains('operation');
사실 이 정도 규모에는 이미 적당한 방법이라고 생각합니다 :)

2022-03-15 15:56 UTC, pocojang commented on src/js/index.js
> +	return Math.trunc(calculator());
그런 코드들을 간혹 `Tricky`하다라고 표현하기는 합니다 ㅎㅎ
재미있고 어떠한 사고나 편견에 가둬지지 않아서 새로운 인사이트를 주죠.

오히려 제가 @younho9 님 덕분에 좋은 인사이트를 받았습니다
스터디에서 활용하기에는 충분히 좋아보입니다 :)
또한 이해도가 있는 사용이기도 했고요

2022-03-15 16:05 UTC, pocojang approved these changes
온보딩 미션에 이렇게 많은 정성드리고 고생 많으셨습니다
재미있는 시도를 정말 많이하셔서 저도 재미있게 봤고요.

고럼 다음 미션부터는 의미 있는 코드와 리얼 월드와 같은 고민을 많이 해보세요 👍 
이만 머지하도록 하겠습니다

2022-03-15 16:05 UTC, pocojang commented on src/js/index.js
> +const state = new Proxy(
아니죠 ㅎㅎ
온보딩 미션인데 이런 저런 다양한 것들 사용해보는거 언제나 환영입니다

2022-03-15 16:05 UTC, merged