[클린코드 2기 이병현] 계산기 미션
next-step/js-calculator pull request #105
Opened 2022-03-13 05:32 UTC by Tolluset

## How to use

```
# To start from local

yarn
yarn start
```

```
# run cypress test

yarn build
yarn cypress:open
```

## 🔥 Projects!
<p align="middle">
  <a href="https://peaceful-cori-b53c5c.netlify.app/">🖥️ 데모 링크</a>
</p>

## 🎯 기능 요구사항

- [x] 2개의 숫자에 대해 덧셈이 가능하다.
- [x] 2개의 숫자에 대해 뺄셈이 가능하다.
- [x] 2개의 숫자에 대해 곱셈이 가능하다.
- [x] 2개의 숫자에 대해 나눗셈이 가능하다.
- [x] AC(All Clear)버튼을 누르면 0으로 초기화 한다.
- [x] 숫자는 한번에 최대 3자리 수까지 입력 가능하다.
- [x] 계산 결과를 표현할 때 소수점 이하는 버림한다.

<br/>

## 📊 테스트 요구사항

- [x] 기능 요구사항에 제시된 7개의 항목에 대해 테스트 케이스를 만든다.

<img width="447" alt="스크린샷 2022-03-13 오후 2 26 39" src="https://user-images.githubusercontent.com/50096419/158046535-d52e5c27-b235-4cec-9a14-33dfb858a3e7.png">

<br/>

2022-03-13 05:46 UTC, Tolluset commented on src/js/Calculator/controller.js
> +  });
이벤트를 받고 처리하는 부분을 분리하였습니다.

2022-03-13 05:46 UTC, Tolluset commented on src/js/Calculator/model.js
> +    const total = eval(this.#inputBuffer.join(''));
- [x] 2개의 숫자에 대해 덧셈이 가능하다.
- [x] 2개의 숫자에 대해 뺄셈이 가능하다.
- [x] 2개의 숫자에 대해 곱셈이 가능하다.
- [x] 2개의 숫자에 대해 나눗셈이 가능하다.

를 eval로 처리하였습니다.

2022-03-13 05:46 UTC, Tolluset commented on src/js/Calculator/model.js
> +  }
- [x] AC(All Clear)버튼을 누르면 0으로 초기화 한다.

초기화 부분입니다.

2022-03-13 05:46 UTC, Tolluset commented on src/js/Calculator/model.js
> +    }
- [x] 숫자는 한번에 최대 3자리 수까지 입력 가능하다.

3자리 수까지 입력 가능하게 하였습니다.

2022-03-13 05:46 UTC, Tolluset commented on src/js/Calculator/model.js
> +    const roundDownTotal = [Math.floor(total)];
- [x] 계산 결과를 표현할 때 소수점 이하는 버림한다.

소수점 이하는 버리고 있습니다.

2022-03-13 05:46 UTC, Tolluset commented on src/js/Calculator/model.js
> +    const total = eval(this.#inputBuffer.join(''));
하다보니 `'연속적인 연산이 가능하다.'` 을 만들게 되었습니다...

2022-03-13 05:46 UTC, Tolluset commented on src/js/Calculator/model.js
> +    }
계산기스러움을 추가하기 위해 `'마지막 값이 연산자인 경우에도 연산이 가능하다.'` 을 추가 하였습니다.

2022-03-13 05:46 UTC, Tolluset commented on src/js/Calculator/model.js
> +    this.#inputBuffer = [''];
연산 후 버퍼를 비워 `'연산 이후 값을 입력하면 새로운 연산과정을 할 수 있다.'` 를 하게 하였습니다.

기존의 방식으로는 연산 후 새로운 값을 입력하면 결과 값을 이용하는 형식이 되어버렸기 때문입니다.

2022-03-13 05:46 UTC, Tolluset commented on src/js/Calculator/model.js
> +      this.#inputBuffer[0] = display;
연산 후 결과값을 바로 쓰는 경우의 `'연산 이후 연산자를 입력하면 새로운 연산과정을 할 수 있다.'` 를 처리하였습니다.

2022-03-13 05:46 UTC, Tolluset commented on src/js/Calculator/model.js
> +  }
0부터 시작하는 숫자는 이상하다고 느꼈기 때문에 `'0을 입력 후 연산과정을 할 수 있다.'` 처리를 추가하였습니다.

2022-03-13 06:45 UTC, yujo11 commented on src/js/Calculator/model.js
> +    const total = eval(this.#inputBuffer.join(''));
`eval`이 편리하긴 하지만 `eval`의 사용은 최대한 지양하는게 좋다고 생각 하는데요. `eval`을 사용하지 않는 방향으로 리팩터링 해보시면 어떨까요?

2022-03-13 06:46 UTC, yujo11 commented on src/js/Calculator/controller.js
> +  });
이벤트 위임을 이용하도록 리팩터링 해보셔도 좋을거 같아요.

2022-03-13 08:03 UTC, yujo11 requested changes
안녕하세요 병헌님! 

먼저 남겨주신 코멘트에 답글을 하나씩 달다가 한번에 확인하시기 불편하실거 같아서 코드 리뷰로 옮겨와서 나머지 코멘트들을 작성했습니다!

사용성을 고려하여 추가적으로 필요한 기능 사항들을 정의하고 구현하신 부분이 좋네요! 👍 👍 👍 

코멘트 확인해주시고 다시 리뷰요청 주시면 감사하겠습니다!

고생하셨습니다 병헌님! 👍 👍 👍

2022-03-13 08:03 UTC, yujo11 commented on .prettierrc
> +}
`prettier`를 사용하셨는데 EOL이 생긴걸보니 프리티어가 제대로 적용되지 않고 있을수도 있겠다는 생각이 드네요

`prettier --write .` 같은 명령어를 통해 전체적으로 코드 포맷팅을 한번 해주시면 좋을거 같아요

2022-03-13 08:03 UTC, yujo11 commented on cypress/integration/calculator.spec.js
> +const checkTotal = (value) => cy.get('#total').should('have.text', value);
깔끔하네요! 👍 👍

2022-03-13 08:03 UTC, yujo11 commented on cypress/integration/calculator.spec.js
> +const checkTotal = (value) => cy.get('#total').should('have.text', value);
`clickNumber` -> `clickOperation(op)` -> `clickNumber` -> `clickOperation("=")` 이렇게 반복되는 작업이 많으니

`someFunction(num1, num2, op)` 이런 식으로 숫자들과 연산자를 넘겨받으면 결과를 리턴해주는 함수를 작성해봐도 좋을거 같아요

2022-03-13 08:03 UTC, yujo11 commented on src/js/Calculator/model.js
> +};
상수의 경우 대문자를 사용해 작성해주시면 일반적인 변수와 더 확실하게 구분할 수 있을거 같네용

2022-03-13 08:03 UTC, yujo11 commented on src/js/Calculator/model.js
> +    if (Object.values(operations).includes(value)) return 'operation';
`Object.values` 메서드가 코드 전체에서 반복적으로 사용되고 있는데 연산자들을 담은 별도의 배열을 만들어서 사용하면 가독성이 더 좋아질거 같습니다!

2022-03-13 08:03 UTC, yujo11 commented on src/js/Calculator/model.js
> +    }
3과 같은 매직넘버도 상수화해서 관리해보면 어떨까요?

2022-03-13 08:03 UTC, yujo11 commented on src/js/Calculator/model.js
> +};
현재 `operations`의 경우 `model.js` 파일에서만 사용되고 있는데 상수를 `constants`와 같은 별도의 폴더에서 관리하면서 test 코드 작성 시에도 활용해보는건 어떨까요?

2022-03-13 08:03 UTC, yujo11 commented on src/js/index.js
> +app();
`index.js`와 `app.js` 파일을 나눠놓으신 이유가 궁금합니다

2022-03-13 08:03 UTC, yujo11 commented on src/js/Calculator/model.js
> +      return alert('숫자를 먼저 입력해주세요!');
사용하지 않을 값을 retrun 할 필요가 있을까요? alert 와 return을 분리하시면 좋을거 같아요

2022-03-13 08:03 UTC, yujo11 commented on src/js/Calculator/model.js
> +  }
만약 이 함수에 타입을 정의한다면 이 함수의 return type을 어떻게 정의할 수 있을까요?

2022-03-13 08:03 UTC, yujo11 commented on src/js/Calculator/model.js
> +    this.#inputBuffer = this.#inputBuffer.map((buf) => buf.replace('X', '*'));
`eval`을 제거한다면 이 부분도 필요가 없어질거 같네요.

2022-03-13 08:03 UTC, yujo11 commented on src/js/Calculator/controller.js
> +  });
이 부분은 별도로 controller를 분리하신 이유가 있을까요? Calculator의 constructor에 들어가도 좋을거 같다는 생각이 들어서 질문 드립니다.

2022-03-13 08:03 UTC, yujo11 commented on src/js/Calculator/model.js
> +  #inputBuffer = [''];
입력되는 값들을 모두 `inputBuffer`에 담아서 관리하시다보니 `inputBuffer`들에 접근을 할 때 index를 이용하게 되면서 현재 어떤 값에 접근하는지(숫자인지, 연산자인지) 알기가 까다로운 부분이 있었습니다.

하나의 `inputBuffer`로 관리하는 방법도 좋지만, 매직넘버를 통해 `inputBuffer`에 계속 접근하고 있는데요. 이를 객체를 통해 관리하거나, 몇 개의 변수로 나눠서 관리하면 더 가독성 좋은 코드를 만드실 수 있을거 같습니다.

2022-03-14 10:30 UTC, tolluset commented on src/js/Calculator/controller.js
> +  });
Calculator라는 클래스는 이벤트에서 받아온 값들을 처리하고 이벤트 자체의 처리는 컨트롤러가 분담하는 것이 여러가지 이벤트가 늘었을 때 사용하기 쉽지 않을까 싶어서 분리하였습니다.

2022-03-14 10:30 UTC, tolluset commented on src/js/index.js
> +app();
굳이 나눌필요는 없지만, 개인적으로 `index.js` 파일이 자바스크립트, 번들러, 개발자들에게 엔트리로써 활용되고, 엔트리로써 활용되는 곳에는 최대한 적은 양의 코드로 길잡이 같은 역할만 해야 한다고 생각하여 app과 index를 분리하였습니다.

2022-03-14 10:30 UTC, tolluset commented on .prettierrc
> +}
https://github.com/next-step/js-calculator/pull/105/commits/2430ae99cf7a2455c96c45fc07fdcd89f4c10a46

수정하였습니다!

2022-03-14 10:30 UTC, tolluset commented on src/js/Calculator/model.js
> +};
https://github.com/next-step/js-calculator/pull/105/commits/f43a1c092ac37460f682ceea90066a1d22d049fb

그러네요 분리하는게 좋아보이네요 감사합니다 👍

2022-03-14 10:30 UTC, tolluset commented on src/js/Calculator/model.js
> +    if (Object.values(operations).includes(value)) return 'operation';
https://github.com/next-step/js-calculator/pull/105/commits/f43a1c092ac37460f682ceea90066a1d22d049fb

확실히 더 좋은것 같습니다 👍 !!

2022-03-14 10:30 UTC, tolluset commented on src/js/Calculator/model.js
> +      return alert('숫자를 먼저 입력해주세요!');
https://github.com/next-step/js-calculator/pull/105/commits/3438a788d13f82c8efc8cde1f52e39474f9d9d63

`false`를 리턴한다는 의미로 사용하였는데, alert를 반환하는게 의미도 없고, 확실히 명시적으로 반환하는게 좋아보이네요 👍

2022-03-14 10:30 UTC, tolluset commented on src/js/Calculator/model.js
> +    }
https://github.com/next-step/js-calculator/pull/105/commits/f43a1c092ac37460f682ceea90066a1d22d049fb

그러게요... 상수화가 좋아보이네요 👍

2022-03-14 10:30 UTC, tolluset commented on src/js/Calculator/controller.js
> +  });
https://github.com/next-step/js-calculator/pull/105/commits/224b9e0a6effa79742086bf903b6585e95c33560

오.. 좋네요 👍 👍 👍

2022-03-14 10:30 UTC, Tolluset commented on cypress/integration/calculator.spec.js
> +const checkTotal = (value) => cy.get('#total').should('have.text', value);
https://github.com/next-step/js-calculator/pull/105/commits/679a036beac2330ebaa9abc0335d373c95bafc1e

모두 다 커버할 순 없지만 좋네요!!! 👍

2022-03-14 10:30 UTC, tolluset commented on src/js/Calculator/model.js
> +  #inputBuffer = [''];
말씀하신대로 조금 알기 까다로울 수는 있지만, 스택같은 형태로 쌓이는 자료구조라 생각하여 하나의 배열로 관리하였습니다.

어떤 값에 접근하는지에 대한 문제는 아래와 같이 해결해봤습니다! 어떠신가요?

```
 while (this.#inputBuffer.length > 1) {
      let total = 0;
      const [prevValue, operator, nextValue] = this.#inputBuffer.splice(0, 3);
      const [prevNum, nextNum] = [Number(prevValue), Number(nextValue)];

      if (operator === OPERATIONS.ADD) total = prevNum + nextNum;
      if (operator === OPERATIONS.SUBSTRACT) total = prevNum - nextNum;
      if (operator === OPERATIONS.MULTIPLY) total = prevNum * nextNum;
      if (operator === OPERATIONS.DIVIDE) total = prevNum / nextNum;

      this.#inputBuffer.unshift(Math.trunc(total));
    }
```

2022-03-14 10:32 UTC, Tolluset commented on src/js/Calculator/model.js
> +    const total = eval(this.#inputBuffer.join(''));
https://github.com/next-step/js-calculator/pull/105/commits/6debf77f5ba02bede662e8b7745704e295a8db7a

`eval`사용하지 않는 쪽으로 변경하였습니다!

2022-03-14 13:44 UTC, yujo11 approved these changes
안녕하세요 병헌님! 

리뷰 남긴 내용들에 꼼꼼하게 코멘트 달아주셔서 감사합니다! 확인하기가 좋았네요!

이번 미션은 이만 merge 하도록 하겠습니다! 고생 많으셨습니다! 👍 👍 👍

2022-03-14 13:45 UTC, merged