[클린코드 3기 조성민] 계산기 미션
next-step/js-calculator pull request #125
Opened 2022-07-03 04:55 UTC by smchoxx

### 안녕하세요! 이번에 클린코드 3기에 참여한 조성민입니다. 잘부탁드립니다🙂

Cypress은 처음 접해보는 만큼 테스트 코드를 작성하면서 미션을 완수하기에 시간이 빠듯할거 같다는 판단하에
미션을 우선적으로 완수했습니다.
리뷰어님께서 리뷰를 남겨주시는 동안 Cypress에 대해 스터디하고 이후 적용해서 다시 한번 PR을 올리겠습니다!

처음 퍼블리셔로 시작하고, 현재는 FE 개발자로써 일을 시작한지 4개월차 새내기입니다.
당연히 꼼꼼하게 봐주시겠지만, 더 많은것을 알고싶고, 많이 얻어가고 싶습니다!  부탁드리겠습니다! 감사합니다
바쁘신 와중에 넥스트스텝 수강생들을 위해 힘써주셔서 감사합니다🙇🏻‍♂️

2022-07-03 05:35 UTC, pocojang requested changes
안녕하세요!
@smchoxx

퍼블리셔에서 FE로 전향하셨다니 축하합니다 🚀

첫 미션은 NEXTSTEP에 적응하기 위한 미션이라 큰 의미는 없답니다.
다만 앞으로 미션을 수행하기 위해 의식적인 훈련을 계속 해보시는게 좋아요.

1. 꼭 필요하지 않은 주석 제거하기
2. 임시 변수 제거하기
3. 테스트 코드 추가하기

위의 3가지만 반영되어도 한결 나아질거에요
그럼 테스트 코드 추가하고 다시 리뷰 요청해주세요 👍

2022-07-03 05:35 UTC, pocojang commented on .prettierrc
> +}
`EOL` 수정해보세요 :)

2022-07-03 05:35 UTC, pocojang commented on .prettierrc
> +  "trailingComma": "es5"
기본 설정과 겹치시는 부분은 제거해도 좋습니다!
또한 일부러 기본 설정의 의존성을 제거하는 경우도 있고요 ㅎㅎ

2022-07-03 05:35 UTC, pocojang commented on index.html
> -    <head>
템플릿의 문제이지만 "ko"로 변경하는 것을 추천합니다 ㅎㅎ

2022-07-03 05:35 UTC, pocojang commented on index.html
> +    <script type="module" src="src/js/index.js" defer></script>
`defer`를 사용하신 이유가 어떻게 되실까요?

2022-07-03 05:35 UTC, pocojang commented on src/js/calculator.js
> +class Calculator {
비즈니스 로직만 딱 모아놓은 느낌이네요
깔끔하게 잘 모아놓으신 것으로 보입니다!

2022-07-03 05:35 UTC, pocojang commented on src/js/calculator.js
> +  add() {
`add`는 추가하다라는 의미가 가득해서 더하기의 느낌이 좀 덜할 것 같네요 :)

2022-07-03 05:35 UTC, pocojang commented on src/js/index.js
> +let input = '';
임시변수를 과감하게 제거해보는게 어떨까요 ㅎㅎ

2022-07-03 05:35 UTC, pocojang commented on src/js/calculator.js
> +export { Calculator };
`default export`로 변경해보는건 어떨까요?

[MDN Export](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/export)

2022-07-03 05:35 UTC, pocojang commented on src/js/index.js
> +      break;
아무런 케이스에 해당하지 않을 경우인 엣지 케이스도 처리해보시는 것을 추천합니다!

2022-07-03 05:35 UTC, pocojang commented on src/js/index.js
> +calculator.addEventListener('click', (e) => {
오호 이벤트 위임을 유도하신걸까요?

2022-07-03 05:35 UTC, pocojang commented on src/js/index.js
> +  let num2 = numbers[1];
명시적인 코드를 위해 [구조 분해 할당](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)을 활용해보세요

2022-07-03 05:35 UTC, pocojang commented on src/js/index.js
> +  if ((num1 && num1.length >= 4) || (num2 && num2.length >= 4)) {
`4`의 의미는 무엇일까요?!
관리될 수 있는 숫자에 대해 생각해보세요!

2022-07-03 07:58 UTC, smchoxx commented on src/js/index.js
> +      break;
@pocojang 엣지 케이스 작성을 깜빡했네요!

2022-07-03 07:59 UTC, smchoxx commented on src/js/index.js
> +calculator.addEventListener('click', (e) => {
@pocojang 네 맞습니다! 숫자,문자,ac 각각을 분리해서 작성하다보니 중복된 코드들이 있어 한층 더 위의 부모에게 이벤트 위임을 해도 괜찮다는 생각에 이렇게 작성해봤습니다🙂

2022-07-03 08:00 UTC, smchoxx commented on src/js/index.js
> +  let num2 = numbers[1];
@pocojang 구조 분해 항당을 사용하는게 코드의 양도 줄고 명시적인 코드가 될거 같네요! 감사합니다

2022-07-03 08:02 UTC, smchoxx commented on src/js/index.js
> +  if ((num1 && num1.length >= 4) || (num2 && num2.length >= 4)) {
@pocojang 세 자릿수가 넘어가면 경고문구를 띄어주기 위해 작성했는데 지금 생각해보니 따로 상수로 빼서 관리하는게 이후 코드를 관리하는데 있어서 효율적일거 같다는 생각이드네요!

2022-07-03 08:03 UTC, smchoxx commented on src/js/calculator.js
> +class Calculator {
@pocojang 감사합니다!🙂

2022-07-03 08:11 UTC, smchoxx commented on index.html
> +    <script type="module" src="src/js/index.js" defer></script>
@pocojang
defer를 사용하지 않을 경우 브라우저는 코드를 읽어 내려가다가 javascript 태그를 만나면 html 파싱을 멈추고 javascript의 코드를 먼저 다 읽고 난 뒤에 뒤에 html 코드를 읽어내려가게 됩니다.
이때, javascript 파일 안에서 body 안에 elements를 조작하는 로직이 있다면 에러가 발생하게 되는데 defer 속성을 사용할 경우 body까지의 랜더링이 모두 끝난뒤에 javascirpt 파일을 실행시키므로 이러한 에러를 방지할 수 있습니다!
이러한 이유로 defer를 사용했습니다!

2022-07-03 08:11 UTC, smchoxx commented on index.html
> -    <head>
@pocojang 변경한다는게 깜빡했네요! 감사합니다ㅎㅎ

2022-07-03 08:13 UTC, smchoxx commented on .prettierrc
> +}
@pocojang 아직 EOL에 대해서 잘 모르지만 한번 수정해보겠습니다! :)

2022-07-03 08:13 UTC, smchoxx commented on .prettierrc
> +  "trailingComma": "es5"
@pocojang 넵! 기본 설정과 겹치는 부분은 제거하는게 좋을거 같네요

2022-07-06 10:54 UTC, pocojang commented on index.html
> +    <script type="module" src="src/js/index.js" defer></script>
근거를 명확하게 설명하시는 점 멋집니다 👍

2022-07-06 10:56 UTC, pocojang approved these changes
@smchoxx 

첫 미션부터 이렇게 꼼꼼히 하시는걸 보니 앞으로 하실 미션이 기대되네요
온보딩 미션이라 깊은 내용의 리뷰는 없었지만 다음 미션부터는 해결해야할 과제가 많으니 다양한 시도를 해보시고 다양한 피드백도 받아보세요

수고하셨습니다 👍

2022-07-06 10:56 UTC, merged