[클린코드 3기 이지수] 계산기 미션
next-step/js-calculator pull request #135
Opened 2022-07-04 04:00 UTC by jisoo-log

안녕하세요 :)
react-native 위주로 개발하다가 react로 넘어와서 어찌저찌 개발은 하고있는 프론트엔드 개발자 이지수입니다.
DOM을 다루는 코드를 거의 써본적이 없고, 회사에서 클래스도 안쓰다보니 어떻게 구조를 가져가야할지에 대해 전혀 감이 없어서 어려웠습니다. 그래서 코드가 다 뭉쳐있는 모양새네요. 이마저도 처음엔 index.js에 전부 다 작성했는데 이건 좀 아닌것 같아서 클래스를 따로 만들었습니다.

코드 리뷰받으려니 너무 부끄럽네요 ㅎㅎ 잘부탁드립니다.

https://user-images.githubusercontent.com/49010073/177078835-792298b1-2fe6-476b-b76a-ddd0906e160f.mov

2022-07-05 11:34 UTC, jho2301 commented on cypress/e2e/spec.cy.js
> +    cy.get('.operation:last-child').click();
nth-child 선택자를 이용하면 html구조를 바꿨을 때에도 테스트가 동작하지 않을 것 같아요. 
깨지기 쉬운 테스트는 유지보수하기가 어렵더라구요
id나 test-id 같이 attribute로 특칭하면 어떨까요

2022-07-05 12:29 UTC, jho2301 requested changes
안녕하세요 지수님!
리뷰어 전환오입니다

구체적 구현에 대해서 추상화를 적절하게 진행해주신 점이 잘 보였던 것 같아요!

테스트도 실제 프로그램코드처럼 적절한 추상화를 시도해보셔도 좋을 것 같다는 생각을 했어요요 부분은 다른 참여자분들 테스트코드를 참고하는게 가장 좋다고 생각해요

클래스의 볼륨이 계산기로직에 비해 상당히 큰 편인데 어떻게 연관된 멤버변수와 메서드로 줄여볼 수 있을지 고려해보시면 좋을 것 같습니다.

감사합니다!

2022-07-05 12:29 UTC, jho2301 commented on cypress/e2e/spec.cy.js
> +    cy.get('.operation:last-child').click();
요렇게 계산을 하는 로직이 테스트마다 반복되고있는데 함수로 추상화하면, 집중하고자하는 부분(assertion)이 더 잘 드러날 것 같아요

2022-07-05 12:29 UTC, jho2301 commented on src/js/Calculator.js
> +  _limit;
private 멤버변수 선언하는 문법이 있어요. 아래 mdn문서 참고해주심 감사하겠습니다!

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

2022-07-05 12:29 UTC, jho2301 commented on src/js/Calculator.js
> +    this._limit = 3;
3과 같은 매직넘버는 상수화해주면 좋을 것 같아요. 재사용성뿐만아니라 가독성도 좋아질듯 해요!

2022-07-05 12:29 UTC, jho2301 commented on src/js/Calculator.js
> +  };
handleAppendDigit이나 appendDigit과 같이 동작을 좀 더 구체적으로 표현해볼 수 있을 것 같아요

2022-07-05 12:29 UTC, jho2301 commented on src/js/Calculator.js
> +    }
else 체이닝은 앞단의 조건을 계속해서 인지한 상태로 다음 조건을 읽어야해서 가독성에 좋지 않다고 생각해요.

return을 통해 else를 제거해보면 어떨까요?

```suggestion
    if (this._limit === 0) {
      alert('숫자는 세자리까지만 입력 가능합니다!');
      return;
    } 
    
    if (this._expression === '0') {
      this._expression = digit.toString();
      return
    } 
    
     this.addExpression(digit);
    
```

2022-07-05 12:29 UTC, jho2301 commented on src/js/Calculator.js
> +    }
checkExpression메서드내에서 resetExpression동작이 이 암묵적으로 보이는데,
checkExpression는 check여부를 return하고 reset동작은 사용하는쪽에서 호출하면 어떨까요?

2022-07-05 12:29 UTC, jho2301 commented on src/js/Calculator.js
> +  };
클래스 볼륨이 꽤 큰데, 이 메서드들은 멤버변수를 따로 사용하지 않고,  클래스에서 분리할 수 있는 순수함수인 것 같아요. 모듈로 분리해보시면 어떨까요??

2022-07-05 12:29 UTC, jho2301 commented on src/js/Calculator.js
> +    }
validation은 상단으로 위치시켜서, 이후에 본동작이 진행되도록 분리시켜주면 어떨까요?

2022-07-05 12:29 UTC, jho2301 commented on src/js/Calculator.js
> +    }
\+ alert -> return 동작이 반복되고 있는데, 반복을 제거해봐도 좋을듯해요

2022-07-05 12:29 UTC, jho2301 commented on src/js/Calculator.js
> +      const { firstNumber, secondNumber } = this.splitNumbers();
expression멤버변수를 보면 계산기 결과창에 노출되는 문자열 그대로를 갖고있어요.
그러다보니까 파싱을 위해 추가적인 코드(splitNumbers)도 필요하고, 관리의 복잡도가 높아지는듯해요.
실제 사용되는 데이터 관점에서 피연산자 2개와 연산자를 데이터로 관리하면 어떨까요?

2022-07-05 12:29 UTC, jho2301 commented on src/js/index.js
> +};
이벤트핸들러의 경우 handle- prefix를 붙여주는게 일반적입니답

2022-07-05 12:29 UTC, jho2301 commented on src/js/index.js
> +operations.addEventListener('click', clickOperation);
addEventListener 호출이 여러 곳에 존재하고 있는데 하나의 함수로 모아보면 어떨까요?

2022-07-06 02:50 UTC, jisoo-log commented on cypress/e2e/spec.cy.js
> +    cy.get('.operation:last-child').click();
넵 다른분 코드를 보고선 수정했습니다

2022-07-06 02:50 UTC, jisoo-log commented on src/js/Calculator.js
> +  _limit;
모르고 있었네요.. 수정했습니다!

2022-07-06 02:50 UTC, jisoo-log commented on src/js/Calculator.js
> +    this._limit = 3;
constants 를 따로 빼긴했는데, 그냥 static 변수를 만드는게 더 나았을까요??

2022-07-06 02:51 UTC, jisoo-log commented on src/js/Calculator.js
> +  };
넵 따로 분리했습니다! 다른분들 코드 보니까 여기도 훨씬 더 간결하긴 하더라고요 ㅎㅎ

2022-07-06 02:52 UTC, jisoo-log commented on src/js/index.js
> +operations.addEventListener('click', clickOperation);
모아서 함수로 만들고 실행시켰는데 보통 이렇게 따로 이벤트 리스너를 모아두고 실행시키는지 궁금합니다.

2022-07-06 02:53 UTC, jisoo-log commented on src/js/Calculator.js
> +      const { firstNumber, secondNumber } = this.splitNumbers();
다른건 대부분 고쳤는데 여기 고치려면 뜯어고칠부분이 많을것 같아서 일단 간단한 부분들 먼저 고쳤습니다 ㅜ 오늘 저녁에 시간이 나면 추가로 해보겠습니다.

2022-07-06 12:03 UTC, jho2301 commented on src/js/Calculator.js
> +    this._limit = 3;
저라면 모듈로 분리했을 것 같긴합니답

2022-07-06 12:10 UTC, jho2301 commented on src/js/index.js
> +operations.addEventListener('click', clickOperation);
단순히 이벤트리스너를 모아서 실행한다는 의미보다는, 프로그램을 초기화하는 로직을 한 개 함수로 모아 관리한다는 느낌으로 생각해주시면 좋을 것 같아요.

2022-11-07 12:10 UTC, merged