[클린코드 4기 이상훈] 계산기 구현
next-step/js-calculator pull request #144
Opened 2022-11-05 12:17 UTC by sanghunlee-711

안녕하세요 리뷰어님! 처음으로 만들어본 계산기라 조건문이 생각보다 난잡하게 짜져있는 것 같습니다 ㅎㅎ..
아래 질문사항 참고하시면서 리뷰 해주시면 감사드리겠습니다!

## 질문사항
- 클래스내의 연산과 이벤트리스너 메서드를 따로 분리해서 작성하였습니다.
 혹시 조금 더 깔끔하거나 간단한 방법이 있으시거나 생각나시면 조언 부탁드립니다!
- Cypress 테스트케이스에서 뭔가 중복된 것이 보일듯 말듯하여 일단은 복사붙여넣기 느낌으로다가 테스트를 작성하였습니다. 이 또한 좋은 의견있으시면 조언 부탁드립니다.

# 🎯 기능 요구사항
- [x] 2개의 숫자에 대해 덧셈이 가능하다.
- [x] 2개의 숫자에 대해 뺄셈이 가능하다.
- [x] 2개의 숫자에 대해 곱셈이 가능하다.
- [x] 2개의 숫자에 대해 나눗셈이 가능하다.
- [x] AC(All Clear)버튼을 누르면 0으로 초기화 한다.
- [x] 숫자는 한번에 최대 3자리 수까지 입력 가능하다.
- [x] 계산 결과를 표현할 때 소수점 이하는 버림한다.

📊 테스트 요구사항
- [x]  기능 요구사항에 제시된 7개의 항목에 대해 테스트 케이스를 만든다.

2022-11-07 23:45 UTC, jho2301 requested changes
안녕하세요 상훈님 
리뷰어로 참여하게 된 전환오라고 합니다!
앞으로 잘 부탁드려요
좀 더 깔끔하게 코드를 구성할 수 있도록 리뷰 남겨봤어요
 참고부탁드립니다 :)

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +    this.total = document.getElementById('total');
```suggestion
class Calculator {
  $target;
  sum;
  operator;
  total;
  
  constructor({ $target }) {
    this.$target = $target;
    this.sum = '';
    this.operator = '';
    this.total = document.getElementById('total');
```

클래스 내에서 사용되는 멤버변수들을 상단에 선언해주면 어떨까요? 보다 명시적으로 나타낼 수 있을 것 같아요.

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +    this.total = document.getElementById('total');
$target으로 최상단 요소를 받아왔으니 $target에서 요소를 찾아도 좋을 것 같습니다. 
전자는 계산기 바깥에 total 요소가 존재하거나, 두 개 이상의 계산기 인스턴스가 만들어지는 경우 의도한대로 동작을 하지 않을 거에요

```js
$target.querySelector('#total');
```

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +  }
일관성있게 형변환을 해주거나 해주지 않는 것이 좋을 것으로 보여요.
해주지 않는 다면 타입에 대한 검증을 하는 것이 보다 변경에 강한 코드가 될 거에요

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +  }
각 메서드들이 메서드명과 같이 의도한 동작 외에 추가적인 동작을 하고 있어요
이를 분리해서 각 메서드들이 한 가지 동작만 수행하도록 변경을 해볼 수 있을까요?

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +    this.operator = '';
데이터가 없음을 나타낼 땐 `null`이나 `undefined`를 활용해볼 수 있어요

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +      element.addEventListener('click', (e) => {
각 요소에 이벤트리스너를 걸어주는 방법도 있지만, 이벤트위임을 통해 구현하는 방법도 구상해보시면 좋을 것 같습니다.
하나의 이벤트리스너로 이터레이션을 돌지 않고 해결할 수 있어요.

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +        );
```suggestion
        const [a, b] = divideOperatorAndNumber(
          this.sum + e.target.innerText
        );
```

사용하지 않을 땐 받지 않아도 됩니다.

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +      element.addEventListener('click', (e) => {
되도록 축약어 보단 풀네임을 작성해주는 것이 가독성에 도움이 됩니다. 

```js
element.addEventListener('click',  async (e) => {
  try {
    await  fetchSomething(e.value);
  catch (e) {
    alert(e.message);
  }
}
```

흔하게 볼 수 있는 코드인데 e가 event와 error의 축약어로 사용되고 있어요. 

```js
element.addEventListener('click',  async (event) => {
  try {
    await  fetchSomething(event.value);
  catch (error) {
    alert(error.message);
  }
}
```

e와 같은 경우 이미 개발자들 사이에선 흔하게 사용되고 있어 받아들여질 수 있는 범주 내라고 볼 수 있지만 의식적으로 해당 코스동안은 연습을 해보시면 어떨까해요

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +        if (a.length > 3 || b.length > 3) {
3은 최대길이를 나타내는 상수로 교체해 의미를 더욱 드러내보면 어떨까요

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +          this.sum + e.target.innerText
버튼텍스트가 숫자만 담고 있기에 innerText를 사용하는 것도 적절할 수 있지만, data 속성을 이용하면 view와 결합되지 않는 코드를 만들 수 있을 거에요

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +        if (this.operator && e.target.innerText !== '=') {
조건문에서는  truthy / falsy 비교를 지양하고  boolean값만 평가될 수 있도록 변경해보면 어떨까요?

2022-11-07 23:45 UTC, jho2301 commented on src/js/calculator.js
> +        if (this.operator && this.sum && e.target.innerText === '=') {
주석으로 나타낼 수도 있지만 조건을 변수로 분리해서 변수명을 통해 의도를 나타낼 수도 있겠습니다

2022-11-07 23:45 UTC, jho2301 commented on cypress/e2e/calculator.cy.js
> +    });
이런 반복되는 테스트동작들도 역시 함수로 분리하면 더욱 좋을 거에요. 테스트도 프로그램코드와 동일하게 스펙의 변경에 따라 계속해서 수정되어야하는 유지보수의 대상이라고 봐주시면 되겠습니다

2022-11-08 00:24 UTC, jho2301 commented on src/js/calculator.js
> +          this.sum + e.target.innerText
https://developer.mozilla.org/ko/docs/Learn/HTML/Howto/Use_data_attributes

2022-11-08 09:49 UTC, sanghunlee-711 commented on src/js/calculator.js
> +    this.total = document.getElementById('total');
확장성을 생각하지 못했네요 감사합니다 :)

2022-11-08 09:50 UTC, sanghunlee-711 commented on src/js/calculator.js
> +      element.addEventListener('click', (e) => {
좋은 생각이신 것 같습니다 ㅎㅎ 적용해보겠습니다

2022-11-08 09:50 UTC, sanghunlee-711 commented on src/js/calculator.js
> +          this.sum + e.target.innerText
dataset을 이용해서 진행해보겠습니다 :)

2022-11-08 09:51 UTC, sanghunlee-711 commented on src/js/calculator.js
> +        if (this.operator && this.sum && e.target.innerText === '=') {
이부분은 이때까지 한번도 생각해보지 못했네요 곧바로 적용해볼게요!

2022-11-08 09:53 UTC, sanghunlee-711 commented on src/js/calculator.js
> +    }
@jho2301  이 부분은 NaN을 판단하는 로직이 어딘가에는 필요하다고 생각되어 setState 진행 시 넣게 되었습니다만.. 함수의 역할에서 엇나가는 것 같아 고민이 되는 부분입니다.
 더 좋은 유효성검사를 할 부분이 있을지 의견 부탁드립니다!

2022-11-08 09:57 UTC, sanghunlee-711 commented on cypress/support/commands.js
> +Cypress.Commands.add('clickNumbers', (numbers) => {
Cypress의 커맨드지원 기능을 통해 반복되는것을 활용한 상태입니다.

실제 프로젝트에서는 이렇게 페이지마다 반복되는 커맨드를 만들다 보면 하나의 커맨드 파일이 너무 커져서 고민이 있습니다.
답변이 가능하시다면 현업에서 커맨드를 혹시 어떻게 관리하시는지 여쭤봐도 될까요?

페이지별 커맨드 파일을 만들고 suppoert/e2e.js 에 여러가지를 임포트하는 방식을 사용하시는지 아니면 하나의 커맨드로 계속 관리를 하시는지.. 아니면 제가 생각못한 방식이 있는지 궁금합니다!

2022-11-08 10:01 UTC, sanghunlee-711 commented on src/js/calculator.js
> +    this.total = document.getElementById('total');
제가 잘못이해한것 일 수도 있을 것 같아 질문하나 남겨봅니다 :)
클래스내에서 멤버변수라하시면 instance화 할 때 사용하지 않고 현재 클래스 내에서만 사용할 변수들을 말하시는 게 맞으신가요??
제안해주신 부분에 전체가 동일하게 들어가있어서 혼동이 조금 있었습니다 🥲

2022-11-12 23:38 UTC, jho2301 commented on src/js/calculator.js
> +    this.total = document.getElementById('total');
@sanghunlee-711 

현재 constructor에서 초기화하는 부분이 존재해서 동일하게 들어가 있다고 볼 수 있지만,
앱의 복잡도가 높아지는 경우 constructor에서 초기화하지 않고 메서드에서 초기화하는 경우도 있을거에요. 상속을 사용할 경우 constructor를 작성하지 않는 경우도 있을테구요. 
그런 관점에서 constructor가 아닌 class의 최상위 레벨에서 멤버변수를 선언해주는 것이 좋다고 말씀드린 부분이었습니다!

constructor에서 무조건 멤버변수를 선언한다는 컨벤션을 가져가신다면 이 또한 괜찮을 수 있는 방향이라고 생각합니다

2022-11-12 23:43 UTC, jho2301 commented on src/js/calculator.js
> +    }
isNaN이 타입에 대한 검사를 한다는 점에서 어떤 함수에 있어도 어색하지 않다는 생각이 들긴하는데요.
일반적으로 검증은 이벤트핸들러에 일임하는게 좋다는 생각입니다! MVC관점에서 이벤트핸들러가 Controller역할을 맡게된다고 생각하는데, controller가 서비스로직에 대한 흐름을 명시적으로 갖고있는 것이 앱의 동작을 쉽게 파악할 수 있도록 작성하는데 가장 좋더라구요

2022-11-12 23:44 UTC, jho2301 commented on src/js/calculator.js
> +    }
\+ 검증함수는 에러를 던져서 동작시 에러를 파악할 수 있도록 의도하는게 보다 좋을 것 같아요

2022-11-12 23:46 UTC, jho2301 commented on cypress/support/commands.js
> +Cypress.Commands.add('clickNumbers', (numbers) => {
현업에서는 싸이프레스를 사용하고 있지 않습니다 ㅎㅎ..
[지역성 원칙](https://ahnheejong.name/articles/package-structure-with-the-principal-of-locality-in-mind/#:~:text=%EB%B0%94%EB%A1%9C%20%EC%A7%80%EC%97%AD%EC%84%B1%EC%9D%98%20%EC%9B%90%EC%B9%99(principal,%ED%95%98%EB%8A%94%20%EA%B2%BD%ED%96%A5%EC%9D%84%20%EC%9D%98%EB%AF%B8%ED%95%9C%EB%8B%A4.)에 따라 사용하는 테스트 파일의 가까이에 두는게 좋겠어요.

2022-11-12 23:50 UTC, jho2301 commented on cypress/support/commands.js
> +Cypress.Commands.add('clickNumbers', (numbers) => {
커맨드의 경우 저는 위 의도로 사용을 별로 좋진 않게 생각하는데요.

clickNumbers는 도메인에 대한 내용을 담고 있다는 점.
때문에 위 커맨드에 대한 맥락이 없는 동료들은 동작확인이 필요할텐데 바로가기가 되지 않으니 함수로 작성하는것이 더 적절하다고 생각합니다.

커맨드는 싸이프레스의 동작을 좀 더 확장하는 개념으로 사용하는게 좋다고 생각해요

2022-11-12 23:51 UTC, jho2301 approved these changes
안녕하세요 상훈님! 남겨주신 질문들에 대한 답을 드려보았습니다 ㅎㅎ. 답이 충분히 되었을지 모르겠네요! 충분치 않다면 dm으로 보내주세요!
수정하신 코드들 모두 확인했으며 이만 머지하도록 하겠습니다 로또 미션도 화이팅입니다 👍

2022-11-12 23:51 UTC, merged