[계산기] 두 개의 숫자에 대해 덧셈, 뺄셈, 곱셈, 나눗셈이 가능하다
next-step/js-calculator pull request #147
Opened 2022-11-06 10:58 UTC by pithesun

2022-11-07 12:17 UTC, pocojang commented
@pithesun 님
LMS에서 미션시작 & 리뷰요청을 해주세요!

2022-11-13 07:52 UTC, pocojang requested changes
@pithesun 👋 
반갑습니다

테스트와 에러처리를 꼼꼼하게 하려는 점이 정말 프로답고 좋네요.
몇가지 리팩터링 방향을 제안드려볼테니 한번 수정해보시면서 코멘트 리뷰도 확인해보세요 :)

1. 모든 `let` 제거
2. 생성자 함수의 메서드 외부 함수 스코프의 `prototype`으로 옮기기 (그 이유도 이해하기)
3. `== 연산자`를 `=== 연산자`로 변경하기 (그 이유도 이해하기)
4. `truthy` & `falsy` 사용해보기

이상입니다!
수정 후 LMS에서 다시 리뷰요청해주세요 :)

2022-11-13 07:52 UTC, pocojang commented on cypress/e2e/spec.cy.js
> +      calculator.setCur(2);
`cur`은 너무 짧아서 문맥 파악이 어려울 것 같은데요?!

2022-11-13 07:52 UTC, pocojang commented on cypress/e2e/spec.cy.js
> +  const calculator = new Calculator();
`before()`와 같은 라이프사이클에 포함시키지 않는 이유가 궁금합니다~

2022-11-13 07:52 UTC, pocojang commented on cypress/e2e/spec.cy.js
> +      expect(actual).to.throw(ERROR_MESSAGE.PARAM_MISSING);
에러를 던지는 테스트가 좋긴한데요
그 경우에 대한 테스트를 검증할 필요도 있어보이네요

2022-11-13 07:52 UTC, pocojang commented on package.json
> +{
오 일부러 이렇게 대부분 비워놓으신걸까요?

2022-11-13 07:52 UTC, pocojang commented on src/js/App.js
> +  const calculatorDiv = $target.querySelector(".calculator");
`Div`와 같은 `HTML Element` 이름이 아닌 다른 맥락의 네이밍은 어떨까요?

2022-11-13 07:52 UTC, pocojang commented on cypress/e2e/spec.cy.js
> +describe("계산기 UI", () => {
와 UI 테스트도 시도하시는군요?
정말 멋집니다
차라리 이런 테스트는 스냅샷 테스팅을 시도해보세요!

2022-11-13 07:52 UTC, pocojang commented on src/js/Calculator.js
> +      let result = func.call(this);
`const`로 변경해도 문제가 없겠네요~?

2022-11-13 07:52 UTC, pocojang commented on src/js/Calculator.js
> +      this.prev == "undefined"
[Truthy](https://developer.mozilla.org/ko/docs/Glossary/Truthy) & [Falsy](https://developer.mozilla.org/ko/docs/Glossary/Falsy)에 대해 참고해보세요 :)

2022-11-13 07:52 UTC, pocojang commented on src/js/Calculator.js
> +    }
- 조건절이 굉장히 늘어지거나 온전한 규칙이 있는 경우 switch~case로 바꾸는건 어떨까요?
- [== 연산자](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Equality)보다는 [=== 연산자](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality)를 사용하는게 더욱 좋습니다 :)

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +  if (!(calculator instanceof Calculator)) {
이제는 새로운 방식인 [new.target](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target)을 사용하실 수 있답니다 :)

또한 어떤 에러를 던져줄지 명시해주는게 어떨까요?
지금은 암시적인 에러를 더지고 있네요!

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +    if (numstr.length > 3) throw new Error(ERROR_MESSAGE.WRONG_NUMINPUT);
`3`이 무엇인지 명시하는게 어떨까요?
아니면 그 이상으로 해당 조건부가 어떤 검사를 하는지 명시해보는 것도 좋아요

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +      throw new Error(ERROR_MESSAGE.WRONG_NUMINPUT);
여기서는 라인이 나뉘는데 `if`문에 중괄호가 있는게 어떨까요?
또한 `undefined`를 문자열로 감싸신 이유가 있으실까요?

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +      : this.calculator.getPrev() || 0;
이런 처리를 실제 메서드 본체에서 하고 있으면 더욱 좋지 않을까요?

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +      alert("=");
이건 테스트 용도일까요?!

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +    let result = this.calculator.cal();
`let`을 사용할 이유가 있을까요?!

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +  this.oonclickModifierEventHandler = (event) => {
`oon` 오타 같군요!

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +    }
이게 리셋의 역할을 하는 함수인거죠?
현재 구조상에서는 함수만 봤을때 맥락을 파악하기 어렵네요!

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +    }
```suggestion
    if (this.calculator.getOperator()) {
      this.calculator.setCur(nextNum);
    } else {
      this.calculator.setPrev(nextNum);
    }
```

이건 어떠세요!?

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +    if (String(nextNum).length > 3) {
세자리수를 구하고 싶은거죠?

2022-11-13 07:52 UTC, pocojang commented on src/js/CalculatorView.js
> +  this.calculator = calculator;
계산기의 어떤 부분을 어떻게 담당하는 것일까요?

2022-11-14 22:31 UTC, pithesun commented on src/js/Calculator.js
> +      let result = func.call(this);
아하 넵넵

2022-11-14 22:39 UTC, pithesun commented on src/js/CalculatorView.js
> +      alert("=");
네! 지워보도록 하겠습니다~!

2022-11-14 22:40 UTC, pithesun commented on src/js/CalculatorView.js
> +    }
오호 읽기 쉬운 것 같아요!

2022-11-17 07:27 UTC, pithesun commented on src/js/CalculatorView.js
> +    if (String(nextNum).length > 3) {
넵..!

2022-11-18 05:02 UTC, pocojang commented on src/js/CalculatorView.js
> +    if (String(nextNum).length > 3) {
그럼 그 의미를 담아서 조건문에 포함하는 것은 어떨까요?!

2022-11-25 23:47 UTC, pocojang approved these changes
@pithesun 👋 
온보딩 미션이기에 이만 머지합니다!
다만 코멘트 리뷰가 많은데 최대한 소화하셔서 로또 미션부터는 잘 반영해보시면 좋겠어요 :)

2022-11-25 23:47 UTC, merged

2022-11-27 06:16 UTC, pithesun commented
> @pithesun 👋 온보딩 미션이기에 이만 머지합니다! 다만 코멘트 리뷰가 많은데 최대한 소화하셔서 로또 미션부터는 잘 반영해보시면 좋겠어요 :)

넵넵!

2022-11-27 08:31 UTC, pithesun commented on src/js/CalculatorView.js
> +      throw new Error(ERROR_MESSAGE.WRONG_NUMINPUT);
undefined를 문자로 감싸야한다고 잘못 생각했었네요. 중괄호 추가하고 여기도 truthy / falsy 로 바꿔서 처리해볼게요!!