[클린코드 4기 이근휘] 계산기 구현
next-step/js-calculator pull request #158
Opened 2022-11-08 04:58 UTC by Geuni620

안녕하세요 리뷰어님!
부족한게 많아서 다른 분들의 코드를 많이 참고했습니다.
진행과정에서 평소와 다르게 적용해보고 싶은 부분은 익숙지 않지만 적용해봤어요.

구현조건 중에 '숫자는 한번에 최대 3자릿 수까지 입력 가능하다'는 버튼이 클릭될 때마다 값의 길이를 체크하고 싶었어요.
전역으로 변수를 선언해주고 하나씩 count하려고 생각했는데, 전역보단 지역변수로 만들고 싶었고,
그러다보니 의도한건 클로저인데, 맞게 작성한건지, 좋은 방법인지는 잘 모르겠어요.
간단하게 작성할 수 있는 방법이 있는데, 괜히 복잡하게 작성한건 아닌가 하는 생각도 들었습니다.

그리고 테스트코드는 처음 작성해봤는데요,,, 아직 모르는게 많습니다.
하나씩 더 추가해보려고 하고 있어요!

개선할 부분 알려주시면 반영해서 빠른시일에 다시 PR 날리겠습니다!
감사합니다 🙏

2022-11-08 12:19 UTC, JunilHwang requested changes
안녕하세요 근휘님! 계산기 미션을 함께하게 된 리뷰어 황준일입니다 🙇‍♂️

전체적으로 네이밍에 대해 신경써주시면 좋을 것 같아요 ㅎㅎ 
일부분은 코드를 봤을 때 쉽게 이해하기 힘든 부분도 있는 것 같아요!
이 외에도 자잘한 피드백 남겼으니 확인 부탁드립니다 🙏

2022-11-08 12:19 UTC, JunilHwang commented on cypress/e2e/spec.cy.js
> +    cy.get("#total").should("have.text", "8");
- 숫자 클릭
- 연산자 클릭

이렇게 두 가지에 대한 함수를 만들어서 관리해주면 테스트 코드가 더 깔끔해질 것 같아요!

2022-11-08 12:19 UTC, JunilHwang commented on cypress/e2e/spec.cy.js
> +  });
`-5 / 2`의 경우 뭐가 나와야할까요!?

2022-11-08 12:19 UTC, JunilHwang commented on src/js/constants/constants.js
> +export const DIVISION = "/";
`Operator.PLUS` `Operator.MINUS` 처럼 namespace를 붙여서 관리해주면 코드를 읽을 때 더 이해하기 쉽고 관리도 쉽지 않을까요!?

- 가령 연산자가 20개쯤 된다면?
- 연산자인지 검증하는 로직이 있다면?

2022-11-08 12:19 UTC, JunilHwang commented on src/js/constants/constants.js
> +export const ALERT_MESSAGE = "숫자는 한번에 최대 3자리 수까지 입력 가능합니다!";
마찬가지로 `Message.INVALID_NUMBER_SIZE` 처럼 표현해주면 어떨까요!?

2022-11-08 12:19 UTC, JunilHwang commented on src/js/index.js
> +export const $total = $("#total");
이것들은 export 하는 이유가 있나요?

2022-11-08 12:19 UTC, JunilHwang commented on src/js/index.js
> +import {handleClickValue} from "./calculator.js.js";
파일 이름이 이상해요!

2022-11-08 12:19 UTC, JunilHwang commented on src/js/calculator.js.js
> +import {$total} from "./index.js";
index.js와 calculator.js가 서로 의존하고 있어요.

index.js에서 export 하는 것들은 다른 파일로 분리해서 관리해주면 어떨까요?

2022-11-08 12:19 UTC, JunilHwang commented on src/js/calculator.js.js
> +};
정확히는 operator에 대한 function map이라서

operatorFunctionMap

처럼 표현해주면 어떨까요?
혹은 "연산자와 연산자의 기능에 대한 맵" 을 표현할 수 있게 이름을 지어주면 좋을 것 같아요!

2022-11-08 12:19 UTC, JunilHwang commented on src/js/calculator.js.js
> +})();
클로저를 사용해주셨군요 👍

2022-11-08 12:19 UTC, JunilHwang commented on src/js/calculator.js.js
> +})();
다만 lengthChecker 보다는 더 구체적인 이름으로 작성해주시면 좋을 것 같아요!

2022-11-08 12:19 UTC, JunilHwang commented on src/js/calculator.js.js
> +  const secondNumber = $total.textContent.split(method).pop();
음... 이 흐름을 이해하기가 힘드네요

method는 operator를 의미하는 것 같고,
firstNumber와 secondNumber는 operator 기준으로 잘라낸 값을 의미하는 게 맞겠죠?

2022-11-08 12:19 UTC, JunilHwang commented on src/js/calculator.js.js
> +  const secondNumber = $total.textContent.split(method).pop();
```suggestion
  const [firstNumber, secondNumber] = $total.textContent.split(method).map(Number);
```
이 부분은 이렇게 표현해도 좋을 것 같아요!

2022-11-08 12:19 UTC, JunilHwang commented on src/js/calculator.js.js
> +  if (operator === "=") {
'='에 대한 상수도 정의해주면 어떨까요?

2022-11-09 16:21 UTC, Geuni620 commented on cypress/e2e/spec.cy.js
> +  });
roundDown이라는 함수를 만들었습니다!
하지만 제가 원하는 방향대로 로직에 적용하진 못했어요...🥲
조금 더 고민해보겠습니다 🙏

2022-11-10 00:44 UTC, JunilHwang approved these changes
안녕하세요 근휘님!
피드백 반영 잘 해주셨네요 👏👏👏
계산기 미션은 온보딩 미션이기 때문에 더 들어가지 않고 여기서 마무리하도록 하겠습니다!

다만 아직 고민해볼 부분이 많이 있어요.
이에 대한 피드백 남겼으니 다음 미션 진행하실 때 참고 부탁드립니다!

다른 미션들도 무사완주 하기를 기원합니다 🙏
감사합니다!

2022-11-10 00:44 UTC, JunilHwang commented on cypress/support/commands.js
> +});
아예 commands를 정의해주셨군요 👍

2022-11-10 00:44 UTC, JunilHwang commented on src/js/calculator.js.js
> +};
이름은 dropDecimal 이라고 해주면 어떨까요?

2022-11-10 00:44 UTC, JunilHwang commented on src/js/calculator.js.js
> +};
그리고 이 함수를 export 하는 이유가 있을까요?

2022-11-10 00:44 UTC, JunilHwang commented on cypress/e2e/spec.cy.js
> +    cy.totalResult(roundDown(2));
roundDown을 여기서 사용하면 테스트를 하는 의미가 없답니다 ㅠㅠ
test는 input에 대한 output이 예측되도록 만들어야하는데
output에다 함수를 씌워버리면 예측이 불가능해요!
그래서 다음과 같이 표현해주면 어떨까요?

```js
  it("5 / 2 의 결과는 소숫점을 버린 2가 된다.", () => {
    cy.clickDigits(5);
    cy.clickOperations(OPERATOR.DIVISION);
    cy.clickDigits(2);
    cy.clickOperations(OPERATOR.EQUALS);
    cy.totalResult(2);
  )};

  it("-5 / 2 의 결과는 소숫점을 버린 -2가 된다.", () => {
    cy.clickDigits(-5);
    cy.clickOperations(OPERATOR.DIVISION);
    cy.clickDigits(2);
    cy.clickOperations(OPERATOR.EQUALS);
    cy.totalResult(-2);
  )}
```

2022-11-10 00:44 UTC, JunilHwang commented on src/js/calculator.js.js
> +};
이제보니 테스트코드에서 사용하려고 했던거군요.. 그렇다면 굳이 export를 하지 않아도 될 것 같아요!

2022-11-10 00:44 UTC, JunilHwang commented on src/js/calculator.js.js
> +    },
`checkForDigits.increase()`
이런 흐름도 부자연스럽게 느껴지네요 ㅎㅎ
`숫자확인.증가`
이렇게 해석이 되거든요!

2022-11-10 00:44 UTC, JunilHwang commented on src/js/calculator.js.js
> +    },
`숫자확인.초기화`

이것도 조금 부자연스럽게 느껴져요!

checkForDigits 말고 더 좋은 이름은 없을까요!?

2022-11-10 00:44 UTC, JunilHwang commented on src/js/calculator.js.js
> +  let DIGIT_NUMBER = 0;
보통 대문자는 상수일 때 사용한답니다!

2022-11-10 00:44 UTC, JunilHwang commented on src/js/index.js
> +import {handleClickValue} from "./calculator.js.js";
파일 이름이 `calculator.js.js` 로 되어있네요!

2022-11-10 00:44 UTC, JunilHwang commented on src/js/index.js
> +import {handleClickValue} from "./calculator.js.js";
calculator에서 DOM에 종속적인 코드와 DOM에 독립적인 코드를 분리해서 서로 다른 파일로 관리해주면 어떨까요!?
그렇게 했을 때 좋은 점은 DOM과 무관하게 테스트코드를 작성할 수 있다는 점입니다.

즉, 현재 작성된 코드들이 정밀하게 테스트가 가능한가? 에 대해서도 고민해보시면 좋을 것 같아요!

2022-11-10 00:44 UTC, merged