요구사항 1, 2, 3, 4, 5, 7 구현
next-step/js-calculator pull request #87
Opened 2022-03-09 07:53 UTC by Minsiki

요구사항 1, 2, 3, 4, 5, 7 구현

2022-03-09 09:27 UTC, yujo11 requested changes
안녕하세요 민식님! 어제 과정이 시작한 것으로 알고 있는데 벌써 미션을 마치고 리뷰 요청을 주시다니 엄청난 실행력이네요! 👍 👍 👍 

### ⚒️ 환경설정

- 전체적으로 코드 컨벤션이 맞지 않고, EOL이 파일마다 들어가 있었어요! 이를 솓쉽게 제거하고 코드의 일관적인 컨벤션을 위해 Prettier와 같은 코드 포맷터를 도입해보실걸 강력 추천드리고 싶습니다!
- 코드에 링크와 함께 코멘트 남겼으니 확인해주세요!

### 🎨 UX

- 처음 숫자를 입력할 때 0이 계속 보이는 부분이나, 숫자를 3개 이상 입력했을 때 `alert`가 나온 이후 숫자가 추가되는 등 직접 이것저것 눌러보면서 테스트할 때 어색한 부분들이 많았어요. 
- 이것 역시 자세한 부분은 아래 코멘트 남겼으니 확인해주시면 감사하겠습니다!

### 📝 요구사항


<img width="452" alt="image" src="https://user-images.githubusercontent.com/61097373/157412205-25cff041-c6ec-4b5b-a4ae-b92316d76639.png">

- 작아서 잘 안 보이셨을 수도 있는데 이번 미션의 경우 기능 요구사항 뿐만 아니라 테스트 요구사항 역시 존재하는데요. 현재는 테스트가 작성되어 있지 않은거 같은데 이 부분도 같이 작성해주시면 좋을거 같습니다!

---

코멘트 남긴 부분 확인하고 다시 리뷰요청 부탁드리겠습니다! 리뷰 내용 중 이해가 안 되거나 구현 시 까다로운 부분들이 있다면 언제든지 편하게 질문 주세요! 

고생하셨습니다! 👍 👍 👍

2022-03-09 09:27 UTC, yujo11 commented on src/js/index.js
> +new Calculator();
파일들에 EOL이 들어가 있네용 `ESLint` 같은 린터나 `Prettier` 같은 코드 포맷터를 함께 사용해보시는 것은 어떨까용?

- [ESLint](https://eslint.org/)
- [Prettier](https://prettier.io/)

2022-03-09 09:27 UTC, yujo11 commented on index.html
> +    <script type="module" src="./src/js/index.js"></script>
`module`로 파일을 나눠서 작성해주셨군요! 👍 👍 👍

2022-03-09 09:27 UTC, yujo11 commented on src/js/component/calculator.js
> +        }
`depth`가  깊어지면서 가독성이 떨어지는거 같아요.

early return 등을 사용해 `depth`를 줄여보는건 어떨까요?

2022-03-09 09:27 UTC, yujo11 commented on src/js/constance/element.js
> +});
`Object.freeze()`를 사용하여 상수 객체를 안전하게 관리하시려고 한거 같아요.

`SELECTORS.CLASS.DIGIT = some_value` 이런 코드를 입력하면 어떻게 동작 할까요?

2022-03-09 09:27 UTC, yujo11 commented on src/js/constance/element.js
> +});
덧붙여서, 상수를 모두 대문자 변수로 관리한다는 컨벤션이 있으신거 같은데 굳이 `Object.freeze()`까지 사용해서 상수를 관리해야 할 필요가 있는지도 조금 의문이 드는 부분이네용

2022-03-09 09:27 UTC, yujo11 commented on src/js/util/index.js
> +export const getInteger = (str) => Number.parseInt(str);
`getInteger`라는 이름이 조금 모호한거 같아요. 문자열을 숫자로 바꿔주는 함수라면 `strToIntger` 등 좀 더 명확한 이름을 고민해볼 수 있을거 같습니다.

덧붙여서, 자바스크립트에서 문자열을 정수로 변환하는 여러 방법들 중 `parseInt`를 사용하신 이유도 궁금합니다!

2022-03-09 09:27 UTC, yujo11 commented on src/js/component/calculator.js
> +        this.$modifiers.addEventListener("click", () => this.onClickModifier());
`addEventListener`에 콜백 함수를 등록할 때 인라인으로 등록을 해서 실제 함수가 하는 역할을 바로 파악하는데 불편함이 생기는거 같아용 

인라인으로 콜백 함수를 등록하신 이유가 있을까요? 콜백함수에서 `Event` 객체를 받아서 핸들링해도 되는 상황인거 같아서 질문 드립니다!

2022-03-09 09:27 UTC, yujo11 commented on src/js/util/index.js
> +export const getInteger = (str) => Number.parseInt(str);
그리고 지금 같은 경우(계산기 미션 내에서)는 크게 상관 없겠지만 str을 Number로 변환하지 못 했을 때의 예외처리도 되어 있으면 좋을거 같습니다!

2022-03-09 09:27 UTC, yujo11 commented on src/js/component/calculator.js
> +        }
```js
const operations = {
      "+": (a, b) => getInteger(a) + getInteger(b),
      "-": (a, b) => getInteger(a) - getInteger(b),
      "X": (a, b) => getInteger(a) * getInteger(b),
      "/": (a, b) => Math.floor(getInteger(a) / getInteger(b)),
};

this.setTotal(operations[this.operation](this.frontNumber, this.backNumber));
```

이런 식으로 Lookup Table을 사용하면 보다 깔끔한 표현이 가능할거 같아요!

2022-03-09 09:27 UTC, yujo11 commented on src/js/component/calculator.js
> +        }
이 부분을 보면서 드는 생각인데 `getInteger`의 역할이 단순히 문자열을 숫자로 변환시켜주는 역할인데 굳이 함수로 분리할 필요가 있을지 궁금하네용

아래와 같이 사용해도 충분할거 같다는 생각이 듭니다!

```js
const operations = {
      "+": (a, b) => Number(a) + Number(b),
      "-": (a, b) => Number(a) - Number(b),
      "X": (a, b) => Number(a) * Number(b),
      "/": (a, b) => Math.floor(Number(a) / Number(b)),
    };
```

또는

```js
    const operations = {
      "+": (a, b) => +a + +b,
      "-": (a, b) => +a - +b,
      "X": (a, b) => +a * +b,
      "/": (a, b) => Math.floor(+a / +b),
    };
```

2022-03-09 09:27 UTC, yujo11 commented on src/js/component/calculator.js
> +        }
<img width="246" alt="image" src="https://user-images.githubusercontent.com/61097373/157409239-7c051ecc-02fc-4862-bb21-7d4dc574e60a.png">

이렇게 처음 숫자를 입력할 때 0이 남아있는건 의도된 동작일까요?

2022-03-09 09:27 UTC, yujo11 commented on src/js/component/calculator.js
> +    }
<img width="242" alt="image" src="https://user-images.githubusercontent.com/61097373/157409341-bdf7d509-61a4-4663-b1de-fddecfb33b47.png">

현재 중복으로 여러 개의 연산자들이 들어가는데 여기에 대한 예외처리도 되면 좋을거 같습니다!

2022-03-09 09:27 UTC, yujo11 commented on src/js/component/calculator.js
> +            this.setTotal(this.getTotal()+digit);
이 부분만 연산자 간 띄어쓰기가 안 되어 있어 코드를 보고 무슨 코드인가 순간 고민 했네요ㅎㅎ

전체적인 컨벤션을 맞추기 위해서도 `Prettier`등 포맷터의 사용을 강력 추천 드립니다!

2022-03-09 09:27 UTC, yujo11 commented on src/js/component/calculator.js
> +        }
<img width="244" alt="image" src="https://user-images.githubusercontent.com/61097373/157409781-36fe51b1-3548-4af3-9e3a-6bb4385e51af.png">

현재 `alert`가 나온 이후에 계속해서 숫자들이 추가 되는데 여기에 대한 예외처리가 필요할거 같습니다!

2022-03-09 09:27 UTC, yujo11 commented on src/js/component/calculator.js
> +        this.$modifiers.addEventListener("click", () => this.onClickModifier());
혹시 `this` 바인딩 관련하여 문제가 발생하는거라면 아래 문서를 참고하시면 도움이 되실거 같습니다!

- https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/this
- https://poiemaweb.com/js-this

2022-03-09 09:27 UTC, yujo11 commented on src/js/component/calculator.js
> +        }
이런 동작들이 어디서 발생하는지 찾기 힘드시다면 먼저 `if-else` 문을 조금 나눠서 `depth`를 줄인 후에 디버깅 하는 방식을 추천드리고 싶습니다!

2022-03-09 09:31 UTC, yujo11 commented
LMS를 보다보니 프로그래밍 요구사항이 존재하네요! 

처음엔 조금 어색할 수도 있지만 이 요구사항들을 지키면서 구현해보는 연습을 하시면 좋을거 같습니다!

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/61097373/157413285-b6a71d16-496f-46fe-911f-772fb7fbff8c.png">

2022-03-09 12:39 UTC, Minsiki commented on src/js/component/calculator.js
> +        }
해당 부분 추가 개발하면서 로직이 너무 복잡한거 같아서 싹 엎어 버렸습니다. ㅎㅎ;;;

2022-03-09 12:40 UTC, Minsiki commented on src/js/constance/element.js
> +});
객체를 상수로 관리할 때 Object.freeze로 사용하는게 안전?하다고 들어서 사용중이였는데 사용할 필요 없나요..?

2022-03-09 12:41 UTC, Minsiki commented on src/js/util/index.js
> +export const getInteger = (str) => Number.parseInt(str);
명명법 관련한 코멘트 감사합니다. 수정하다보니 getInteger 이 부분 사용하지 않는 방법을 찾아서 수정하였습니다.

2022-03-09 12:44 UTC, Minsiki commented on src/js/component/calculator.js
> +        this.$modifiers.addEventListener("click", () => this.onClickModifier());
이 부분은 역할별? element에 이벤트를 따로 주고 싶어서 개발했던 부분이였는데 한번에 root 느낌인 calculator에 addEventListener를 하면서 각각 element에 event 핸들링할 수 있도록 수정해보았습니다.

2022-03-09 12:44 UTC, Minsiki commented on src/js/component/calculator.js
> +        }
이 부분 정말 좋은것 같습니다. 코드도 간결하고 가독성도 .. 엄청나네요.... 많이 배웠습니다.

2022-03-09 12:45 UTC, Minsiki commented on src/js/component/calculator.js
> +    }
연산시 연산자 2개 이상 입력되지 않게 수정하였습니다.

2022-03-09 12:46 UTC, Minsiki commented on src/js/component/calculator.js
> +            this.setTotal(this.getTotal()+digit);
Prettier 사용이 익숙지 않은데 한번 사용해 보도록하겠습니다...

2022-03-09 12:49 UTC, Minsiki commented
코드가 전반적으로 많이 미흡했늗네 꼼꼼히 봐주셔서 감사합니다.

2022-03-12 00:18 UTC, yujo11 commented on src/js/constance/element.js
> +});
위에 남긴건 제 주관적인 의견입니다! 민식님께서 Object.freeze를 사용해서 관리하는게 더 안정적이라고 느끼신다면 사용하시면 될거 같습니다!

다만, `Object.freeze()`를 사용했을 때 뎁스가 더 들어가있는 key (ex) `SELECTORS.CLASS.DIGIT`를 변경할 경우 변경이 되는걸 확인하실 수 있을겁니다. 

depth와 상관없이 Object를 `readonly` 상태로 변경하기 위해서는 라이브러리를 사용하거나 재귀적으로 `Object.freeze()`를 사용해 객체 안에 존재하는 객체들도 `freeze` 해줘야 하는데요. 이미 상수를 모두 대문자로 관리하는 컨벤션을 가지고 계시기 때문에 이런 작업을 굳이 해야할까? 하는 생각에 남긴 의견이었습니다!

2022-03-12 00:48 UTC, yujo11 requested changes
안녕하세요 민식님! 

이전 리뷰 때 코멘트로 요청 드린 사항이 많아 리팩터링이 쉽지 않으셨을텐데, 빠르게 반영해주셔서 감사합니다! 

지난 리뷰 때 말씀 못 드린 부분들도 수정되어 있는걸 보고 아마 민식님이 다른 참여자 분들의 코드와 리뷰까지 보면서 공부하고 계신거 같다는 생각이 들었네요! 정말 멋지십니다!! 👍 👍 👍 

코드와 UX 모두 1차 리뷰 때와 비교하여 장족의 발전을 이뤄내신거 같습니다!

다만, 조금 아쉬운 부분이 있다면 환경설정과 관련한 부분인데요. `eslint`의 경우 `configuration` 파일이 2개가 존재하고 있고, `package.json`의 경우에도 필요한 패키지들이 알맞게 설치되지 않은거 같아용. 아마 민식님께서도 이게 동작하는게 맞나? 하는 의문을 가지셨을수도 있을거 같네요ㅎㅎ

이 부분은 앞으로 미션을 진행하시고, 개발을 하시는데 있어서 한번 익혀두면 계속 써먹을 수 있는 유용한 부분이라고 생각합니다!! 처음에는 용어부터 명령어까지 모두 낯설게 느껴지실 수도 있지만 eslitnt, prettier 세팅 관련 키워드로 검색해서 나오는 글을 몇개 보시면 금방 익히실 수 있을거에요! 

이번 계산기 미션이 처음 시작하는 미션이니만큼 이 부분을 한번 꼭 해보셨으면 해서 Request Changes를 남깁니다! 

고생 많으셨습니다! 👍 👍 👍 

ps. 현재 테스트코드의 경우 "성공"하는 케이스 밖에 존재하지 않는데 "실패"하는 케이스에 대한 테스트코드도 작성해보시면 좋을거 같습니다!

ps2. 현재 민식님의 commit log를 보면 어떤 commit에서 어떤 작업이 이뤄졌는지 알기 힘들게 되어있습니다. commit을 조금 더 작은 단위로 나눠보시는 연습을 해보는 것도 좋을거 같아요!

2022-03-12 00:48 UTC, yujo11 commented on .eslintrc.json
> +    }
요건 하나의 팁인데요! 지금과 같이 명확하게 depth의 제한이 요구사항에 있는 경우 eslint의 `max-depth`를 설정해서 depth를 체크할 수도 있습니다!

- https://eslint.org/docs/rules/max-depth

이외에도 상황에 따라 유용하게 사용할 수 있는 룰들이 많이 존재하니 상황에 따라서 찾아보고 적용해보시면 좋을거 같아요! 👍 👍 👍

2022-03-12 00:48 UTC, yujo11 commented on .eslintrc.js
> +};
`eslintrc.js` 파일과 `eslintrc.json` 파일이 모두 존재하네요

동일한 디렉토리에 config 파일이 여러개 존재하면 eslint는 하나의 config 파일만 사용하기 때문에 config파일을 2개 작성하실 필요는 없을거 같습니다. 아래 링크도 참고해보시면 좋을거 같아요!

- https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-file-formats

2022-03-12 00:48 UTC, yujo11 commented on package.json
> +  },
`dependencies`에 `yarn`이 들어있을 필요가 있을까요?

2022-03-12 00:48 UTC, yujo11 commented on .eslintrc.js
> +  extends: ['plugin:cypress/recommended', 'airbnb-base', 'prettier'],
이렇게 extends에 여러 옵션들을 설정해두더라도 해당 패키지가 설치되어 있지 않다면 무용지물일거 같아용.

조금 낯서실 수도 있겠지만 eslint, prettier 세팅 관련 글을 검색해보고 한, 두번 따라해보시면 금방 익히실 수 있을거라 생각합니다!

2022-03-12 00:48 UTC, yujo11 commented on src/js/constant/index.js
> +export const EQUAL = "=";
연산자들도 상수화 시키셨군요! 좋네요! 👍 👍 👍

2022-03-12 00:48 UTC, yujo11 commented on src/js/component/calculator.js
> +        this.$calculator.addEventListener("click", (event) => this.onClick(event));
이벤트 위임을 사용도록 리팩터링 하셨군요 멋지네요!! 👍 👍 👍

2022-03-12 00:48 UTC, yujo11 commented on src/js/constant/index.js
> +export const INIT_DIGIT = "0";
매직 넘버들을 상수화 하신 부분도 좋네요! 👍 👍 👍

2022-03-12 00:48 UTC, yujo11 commented on src/js/component/calculator.js
> +        return this.getTotal().split("").filter(v => isNaN(parseInt(v))).length > 0;
`isNaN`과 `Number.isNaN`의 차이를 알고 계신가용

2022-03-12 05:03 UTC, Minsiki commented on src/js/component/calculator.js
> +        return this.getTotal().split("").filter(v => isNaN(parseInt(v))).length > 0;
몰랐던 부분을 찾아보니까 `isNaN`  보다는 `Number.isNaN`를 권장한다고 하네요. `isNaN` 은 값을 강제 형변환하여 NaN check하면서 정확한 값을 추출할 수 없는 경우가 있다고 하네요. 디테일하게 봐주셔서 감사합니다!

2022-03-13 08:11 UTC, yujo11 approved these changes
안녕하세요 민식님!

벌써 3번째 리뷰네요! 첫 리뷰와 비교했을 떄 코드가 정말 몰라보게 변한거 같습니다! 코드를 리팩터링 하기 위해 정말 많은 노력을 기울이신게 느껴지네요!! 👍 👍 👍 

이번 계산기 미션은 이만 여기서 merge 하도록 하겠습니다! 간단한 코멘트를 남겼는데 다음 번 미션들을 진행하실 때 참고해보시면 좋을거 같습니다!

정말정말 고생 많으셨습니다! 👏👏👏

2022-03-13 08:11 UTC, yujo11 commented on package.json
> +    },
👍👍👍👍👍

2022-03-13 08:11 UTC, yujo11 commented on cypress/integration/test/calculator.spec.js
> +        cy.get("[data-test=btn-equal]").click();
`숫자 클릭 -> 연산자 클릭 -> equal 클릭` 이 일련의 작업들이 테스트 코드 안에서 여러 번 반복되는데요. 이렇게 공통되는 부분을 함수로 분리해서 사용해보셔도 좋을거 같습니다!

2022-03-13 08:11 UTC, yujo11 commented on index.html
> +                    <button data-test="btn-0" class="digit">0</button>
`data-*` 어트리뷰트를 사용하셨군요! 👍 👍 👍

2022-03-13 08:12 UTC, merged